### ISSUE TITLE
onCreate stream example

### ISSUE THREAD

**Issue by rafal-przybylak** [onixjs/examples#9]
Hi,
Could you give an example using the onCreate stream on the client side?

**Comment by jonathan-casarrubias** [comment]
Hi @rafal-przybylak thanks for reaching out,

Hey so, sure I think we can update the client examples to also use the onCreate stream.  In terms of functionality, it basically is just another stream and all of them works the same... But I think is valuable to show more than 1 case of usage, so we are very close to publishing the beta version.

After that, we will immediately update the examples with more advanced features.

Any comment or feedback is pretty welcome.

Cheers
Jon
